### ISSUE TITLE
About evaluator.py

### ISSUE THREAD

**Issue by Monstarrr** [bepoetree/MTTOD#12]
Hi, there! 

I was confused by line [386-387] in your  evaluator.py。
```
if t == 0:
      continue
```
Why do you not use the first turn into evaluation? After removing this line, the score raises about 1 point.

**Comment by bepoetree** [comment]
I followed other evaluation scripts (such as [UBAR](https://github.com/TonyNemo/UBAR-MultiWOZ/blob/master/eval.py#L552), [DAMD](https://github.com/thu-spmi/damd-multiwoz/blob/master/eval.py#L550)) for fair comparison.

This code might be related to MATCH measurement computed as:
https://github.com/bepoetree/MTTOD/blob/61992c60c41f1b4bb3185c769b1a149a24007d21/evaluator.py#L494-L497

Since the offered venues are obtained using belief state, the belief state in the first turn has advantage.

For example, when the predicted belief state is `[area = north]` and the goal is `[area = north, pricerange=expensive]`, the MATCH score increases because the predicted belief state is a superset of goal. 

Thus it is helpful to skip the first turn to solve this issue. Nevertheless, it does not consider very simple dialogues such as one or two turn dialogues.

I recommend to use the improved evaluation tool for benchmark [here](https://github.com/Tomiinek/MultiWOZ_Evaluation)

I hope this will be of help to you :)

**Comment by Monstarrr** [comment]
> I followed other evaluation scripts (such as [UBAR](https://github.com/TonyNemo/UBAR-MultiWOZ/blob/master/eval.py#L552), [DAMD](https://github.com/thu-spmi/damd-multiwoz/blob/master/eval.py#L550)) for fair comparison.
> 
> This code might be related to MATCH measurement computed as:
> 
> https://github.com/bepoetree/MTTOD/blob/61992c60c41f1b4bb3185c769b1a149a24007d21/evaluator.py#L494-L497
> 
> Since the offered venues are obtained using belief state, the belief state in the first turn has advantage.
> 
> For example, when the predicted belief state is `[area = north]` and the goal is `[area = north, pricerange=expensive]`, the MATCH score increases because the predicted belief state is a superset of goal.
> 
> Thus it is helpful to skip the first turn to solve this issue. Nevertheless, it does not consider very simple dialogues such as one or two turn dialogues.
> 
> I recommend to use the improved evaluation tool for benchmark [here](https://github.com/Tomiinek/MultiWOZ_Evaluation)
> 
> I hope this will be of help to you :)

I got your point then. But I was confused by this for I found that in GALAXY and PPTOD, they just added an nonsense dial in the first turn and then used the same evaluation script as yours. 

```
 for dial_id, turns in result_dict.items():
      entry = {'dial_id': dial_id, 'trun_num': len(turns)}
      for f in field[2:]:
          entry[f] = ''
      results.append(entry)
```

**Comment by bepoetree** [comment]
I don't have any idea on their codes..

But I think it would be okay if they compute the MATCH score by checking if the offered venues are a subset of goal venues like [here](https://github.com/Tomiinek/MultiWOZ_Evaluation/blob/master/mwzeval/metrics.py#L233).

**Comment by Monstarrr** [comment]
Also, I cannot find the code same as  "skip the first turn" in the official evaluation script as you mentioned above. 

Thanks for your reply. And I think might the official evaluation script can only be the fair evaluation like you said.

**Comment by Monstarrr** [comment]
> len(venue_offered[domain]) > 0
